# Generated by Django 4.2.6 on 2023-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile_number', models.CharField(max_length=25)),
                ('email_address', models.EmailField(max_length=254)),
                ('email_subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
